class AppRoutes {
  static const login = '/login';
  static const home = '/home';
  static const terms = '/terms_of_service';
  static const welcome = '/welcome';
  static const username = '/username';
  static const avatar = '/avatar';
  static const invitation = '/invitation';
  static const notificationsPermission = '/notifications_permission';
  static const createPost = '/create_post';
  static const settings = '/settings';
  static const profile = '/profile';
  static const editProfile = '/edit_profile';
  static const search = '/search';
  static const searchByGenre = '/search_by_genre';
  static const createFeed = '/create_feed'; // FeedEditorView (creation)
  static const editFeed = '/edit_feed'; // FeedEditorView (editing)
  static const feedRequests = '/feed_requests';
  static const subscriptions = '/subscriptions';
  static const subscribers = '/subscribers';
  static const feed = '/feed';
  static const post = '/post';
  static const report = '/report';
  static const aboutUs = '/about_us';
  static const contacts = '/contacts';
  static const inviteFriends = '/invite_friends';
  static const staff = '/staff';
  static const staffDashboard = '/staff_dashboard';
  static const staffReports = '/staff_reports';
  static const staffFeedbacks = '/staff_feedbacks';
  static const photoViewer = '/photo_view';
  static const appColor = '/app_color';
}
