// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGAkp4zZZm_9EQYt-AZ8GSfsALJRwKkuA',
    appId: '1:1038917266721:web:8327e8923c58e861a46260',
    messagingSenderId: '1038917266721',
    projectId: 'hoot-1cd96',
    authDomain: 'hoot-1cd96.firebaseapp.com',
    storageBucket: 'hoot-1cd96.appspot.com',
    measurementId: 'G-SC5PPSSLKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKuNJ1wll_uJZQStZoqVoNtMpguLXqBbQ',
    appId: '1:1038917266721:android:4b1fad63323d27c2a46260',
    messagingSenderId: '1038917266721',
    projectId: 'hoot-1cd96',
    storageBucket: 'hoot-1cd96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnfxvwEYAkFGxYmoKd03VPyXoATuMCXZw',
    appId: '1:1038917266721:ios:32487bd3410dec21a46260',
    messagingSenderId: '1038917266721',
    projectId: 'hoot-1cd96',
    storageBucket: 'hoot-1cd96.appspot.com',
    androidClientId: '1038917266721-0m2p11r7kmcqf7hibcambi3kfe3rjaia.apps.googleusercontent.com',
    iosClientId: '1038917266721-bt8q5uhgll2tv5ksju28rdbjb0ksvcnn.apps.googleusercontent.com',
    iosBundleId: 'com.hoot.app.hoot',
  );
}
