// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC52jHDXzDDKbHH1Pp0ZcOQgvJxbKNu1T4',
    appId: '1:889498016095:web:56085f96881d72d0967eea',
    messagingSenderId: '889498016095',
    projectId: 'hoot-9f14f',
    authDomain: 'hoot-9f14f.firebaseapp.com',
    storageBucket: 'hoot-9f14f.firebasestorage.app',
    measurementId: 'G-83CZ020RGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2SbYUCJ_hNQLWLQbE8uFcUk_5PkpHCV4',
    appId: '1:889498016095:android:1834e0186fcfa438967eea',
    messagingSenderId: '889498016095',
    projectId: 'hoot-9f14f',
    storageBucket: 'hoot-9f14f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgT_ZOnvk5-WcbQcIT9KY1YJ-Sn0iPM-Y',
    appId: '1:889498016095:ios:e768c47952ab3420967eea',
    messagingSenderId: '889498016095',
    projectId: 'hoot-9f14f',
    storageBucket: 'hoot-9f14f.firebasestorage.app',
    iosClientId: '889498016095-t9qt1bl16fj3qrb4hq3ps1jngn3utkmr.apps.googleusercontent.com',
    iosBundleId: 'com.hoot.app.hoot',
  );

}